default_platform(:ios)

platform :ios do
  desc "Build, sign, and upload to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: false
    )

    build_app(
      scheme: "RTScan",
      export_method: "app-store",
      output_directory: "build",
      xcargs: "DEVELOPMENT_TEAM=#{ENV['APPLE_TEAM_ID']}",
      export_options: {
        provisioningProfiles: {
          (ENV["APP_IDENTIFIER"] || "com.sangkyul.rtscan") => lane_context[SharedValues::SIGH_PROFILE_NAME]
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
